 
name: Process

on: [push, pull_request]

jobs:
  build:
    name: Process

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install geos
        run: |
          sudo apt-get install libgeos-dev
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Install latest shapely
        run: |
          python -m pip install --upgrade cython numpy
          git clone https://github.com/Toblerity/Shapely.git
          cd Shapely
          pip install -v -e .[all]
          cd ..
          
      - name: Checkout ELI
        run: |
          git clone --depth=1 --branch=gh-pages https://github.com/osmlab/editor-layer-index.git
  
      - name: Run processing
        run: |
          python process_eli.py

      - name: Transform geojson to flatgeobuffer
        run: |
          ogr2ogr -f FlatGeobuf -lco SPATIAL_INDEX=YES imagery.fgb imagery.geojson
